### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by quantumgolem** [jstrieb/panopto-download#2]
Hi! I tried running this, but get the following error:

    xargs: max. processes must be >0
    Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
    BrokenPipeError: [Errno 32] Broken pipe

I'm using the following command:

    python3 panopto-video-urls.py -x "http://<some link>" | xargs -L 2 -P 0 wget -O

but with my link. Any help would be appreciated. Thanks!

**Comment by jstrieb** [comment]
Hi, some systems (particularly OS X, I think) don't work with `-P 0`. In that case, just set the number of processes to some number between 4 and 32. For example:

```
python3 panopto-video-urls.py -x "http://<some link>" | xargs -L 2 -P 8 wget -O
```

Happy to help if that doesn't work.

**Comment by jstrieb** [comment]
Hi, @sn0wyfall! Did this resolve your problem? If so, I will close the issue on the repository.

**Comment by quantumgolem** [comment]
Hey, thanks for the reply! I just tried it out again. I don't get the error anymore, but I don't get any output at all. Just to be clear, I'm using the URL of the RSS feed (the one I get from the address bar) when the RSS page is showing. Not sure what else to do now!

**Comment by jstrieb** [comment]
The only thing that I can think to test is to try doing 

``` bash
python3 panopto-video-urls.py -x "<your URL>"
```

without the `xargs` part. If you are getting output from that that looks like the following, then the script should be working fine.

```
"Getting_Started_View_a_Video.mp4"
https://[REDACTED]/4657-9051-abc80159d179.mp4?mediaTargetType=videoPodcast
"Getting_Started_Record_a_Video.mp4"
https://[REDACTED]/b3c6-abc8015a3922.mp4?mediaTargetType=videoPodcast
[ ... ]
```

Note: the URL I am using looks like the following. If yours seems to be structured differently, that may be the problem.

```
http://<university>.hosted.panopto.com/Panopto/Podcast/Podcast.ashx?courseid=<long UUID>&type=mp4
```

**Comment by quantumgolem** [comment]
I got it, thanks a lot! It turns out when I was pasting the URL into iTerm2 (even in quotes) it was adding a bunch of slashes and as a result there was no output. 

The videos download now! On a different note, I realized that these videos are much lower quality than the ones that are actually streamed. I have been able to download these videos in their original quality using a Chrome extension (it was a download manager extension, unfortunately the vast majority of the video downloader extensions don't work). Do you think it'd be possible to get the original quality somehow using the script?

**Comment by jstrieb** [comment]
Glad to hear you got it working! I have no idea why the video quality would be different for the ones on the RSS feed, sorry.

I am closing this issue now.
