### ISSUE TITLE
Does using more processes actually download faster?

### ISSUE THREAD

**Issue by jxu** [jstrieb/panopto-download#5]
From my experience, the bandwidth from panopto's servers is fixed, and hammering the server with many video downloads is not actually faster (the total amount of data being downloaded at once is the same). Also, my shell doesn't display wget's progress bar nicely.

**Comment by jstrieb** [comment]
Having 1000 processes would not be faster than 100, but having 4 is definitely faster than having 1. At least on my network, a couple of basic tests confirm this.

In other words, having more processes is helpful, but only to a point.

Regarding the `wget` progress bar: I recommend also adding the `--quiet` flag. Perhaps I should add a note about that to the main documentation.
